---

- name: download tigerjython logo
  get_url:
    url: http://www.tigerjython.ch/lernumgebung/bilder/tjlogo.png
    dest: '/usr/share/pixmaps/tjlogo.png'

- name: create desktop Entry
  copy:
    src: tigerjython.desktop
    dest: /usr/share/applications/
